const recipes = [
  {
    title: 'Chicken Rice Bowl',
    description: 'A comforting one-bowl meal of seared chicken, fluffy rice and a savory garlic-soy glaze.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chicken', quantity: 300, unit: 'g', category: 'meat-protein' },
      { name: 'rice', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'tomato', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'vegetables' },
      { name: 'soy sauce', quantity: 30, unit: 'ml', category: 'pantry' },
      { name: 'sesame oil', quantity: 10, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Cook the rice according to package instructions and set aside.',
      'Heat oil in a pan and sauté chopped onion and garlic until fragrant.',
      'Add diced chicken and cook until golden and cooked through.',
      'Stir in chopped tomato, soy sauce and sesame oil; simmer for 3 minutes.',
      'Serve the chicken mixture over the rice.',
    ],
    cuisine: 'asian', category: 'dinner', difficulty: 'easy',
    prepTime: 10, cookTime: 20, servings: 2,
    nutrition: { calories: 520, protein: 38, carbs: 55, fat: 14 },
    dietaryTags: ['high-protein'], allergens: ['soy'], rating: 4.6, popularity: 9,
  },
  {
    title: 'Classic Margherita Pizza',
    description: 'Thin crispy crust topped with San Marzano tomato sauce, fresh mozzarella and basil.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'pizza dough', quantity: 1, unit: '', category: 'pantry' },
      { name: 'tomato', quantity: 3, unit: '', category: 'vegetables' },
      { name: 'mozzarella', quantity: 200, unit: 'g', category: 'dairy' },
      { name: 'basil', quantity: 10, unit: 'leaves', category: 'spices' },
      { name: 'olive oil', quantity: 20, unit: 'ml', category: 'pantry' },
      { name: 'garlic', quantity: 2, unit: 'cloves', category: 'vegetables' },
    ],
    instructions: [
      'Preheat oven to 250°C (480°F) with a pizza stone or tray inside.',
      'Blend tomatoes with garlic and a pinch of salt for the sauce.',
      'Stretch the dough and spread the sauce evenly.',
      'Top with torn mozzarella and drizzle with olive oil.',
      'Bake for 8-10 minutes until the crust is golden and blistered.',
      'Finish with fresh basil leaves before serving.',
    ],
    cuisine: 'italian', category: 'dinner', difficulty: 'medium',
    prepTime: 20, cookTime: 10, servings: 2,
    nutrition: { calories: 640, protein: 24, carbs: 78, fat: 22 },
    dietaryTags: ['vegetarian'], allergens: ['dairy', 'gluten'], rating: 4.8, popularity: 10,
  },
  {
    title: 'Paneer Butter Masala',
    description: 'Rich, creamy tomato gravy with soft paneer cubes — a North Indian classic.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'paneer', quantity: 250, unit: 'g', category: 'dairy' },
      { name: 'tomato', quantity: 4, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'garlic', quantity: 4, unit: 'cloves', category: 'vegetables' },
      { name: 'ginger', quantity: 1, unit: 'inch', category: 'spices' },
      { name: 'butter', quantity: 40, unit: 'g', category: 'dairy' },
      { name: 'cream', quantity: 60, unit: 'ml', category: 'dairy' },
      { name: 'garam masala', quantity: 5, unit: 'g', category: 'spices' },
    ],
    instructions: [
      'Sauté onion, ginger and garlic in butter until soft.',
      'Add tomatoes and cook down into a thick sauce, then blend smooth.',
      'Return sauce to the pan, add garam masala and simmer.',
      'Fold in paneer cubes and cream; simmer 5 minutes.',
      'Serve hot with naan or rice.',
    ],
    cuisine: 'indian', category: 'dinner', difficulty: 'medium',
    prepTime: 15, cookTime: 25, servings: 3,
    nutrition: { calories: 480, protein: 18, carbs: 20, fat: 34 },
    dietaryTags: ['vegetarian', 'gluten-free'], allergens: ['dairy'], rating: 4.7, popularity: 9,
  },
  {
    title: 'Vegan Buddha Bowl',
    description: 'A colorful bowl of roasted vegetables, chickpeas and quinoa with tahini dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'quinoa', quantity: 150, unit: 'g', category: 'pantry' },
      { name: 'chickpeas', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'sweet potato', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'spinach', quantity: 50, unit: 'g', category: 'vegetables' },
      { name: 'tahini', quantity: 30, unit: 'g', category: 'pantry' },
      { name: 'lemon', quantity: 1, unit: '', category: 'fruits' },
    ],
    instructions: [
      'Roast diced sweet potato at 200°C for 20 minutes until caramelized.',
      'Cook quinoa according to package directions.',
      'Whisk tahini with lemon juice and water into a smooth dressing.',
      'Assemble quinoa, roasted sweet potato, chickpeas and spinach in a bowl.',
      'Drizzle with tahini dressing before serving.',
    ],
    cuisine: 'mediterranean', category: 'lunch', difficulty: 'easy',
    prepTime: 15, cookTime: 20, servings: 2,
    nutrition: { calories: 460, protein: 16, carbs: 62, fat: 16 },
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], allergens: ['sesame'], rating: 4.5, popularity: 7,
  },
  {
    title: 'Classic Beef Tacos',
    description: 'Seasoned ground beef in crisp corn tortillas with fresh pico de gallo.',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'ground beef', quantity: 300, unit: 'g', category: 'meat-protein' },
      { name: 'corn tortilla', quantity: 6, unit: '', category: 'pantry' },
      { name: 'tomato', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'lime', quantity: 1, unit: '', category: 'fruits' },
      { name: 'cheddar cheese', quantity: 100, unit: 'g', category: 'dairy' },
      { name: 'cumin', quantity: 5, unit: 'g', category: 'spices' },
    ],
    instructions: [
      'Brown the ground beef with cumin, salt and pepper.',
      'Warm the tortillas in a dry pan.',
      'Dice tomato and onion, squeeze over lime juice for a quick pico de gallo.',
      'Fill tortillas with beef, top with cheese and pico de gallo.',
    ],
    cuisine: 'mexican', category: 'dinner', difficulty: 'easy',
    prepTime: 10, cookTime: 15, servings: 3,
    nutrition: { calories: 560, protein: 32, carbs: 38, fat: 30 },
    dietaryTags: [], allergens: ['dairy'], rating: 4.6, popularity: 8,
  },
  {
    title: 'Egg & Veggie Breakfast Toast',
    description: 'Crispy toasted bread topped with a fried egg, tomato and sautéed onion.',
    image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices', category: 'pantry' },
      { name: 'egg', quantity: 2, unit: '', category: 'meat-protein' },
      { name: 'tomato', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 0.5, unit: '', category: 'vegetables' },
      { name: 'butter', quantity: 10, unit: 'g', category: 'dairy' },
    ],
    instructions: [
      'Toast the bread slices until golden.',
      'Sauté sliced onion and tomato in butter until soft.',
      'Fry the eggs to your liking.',
      'Top the toast with the vegetables and egg. Season and serve.',
    ],
    cuisine: 'continental', category: 'breakfast', difficulty: 'easy',
    prepTime: 5, cookTime: 10, servings: 1,
    nutrition: { calories: 340, protein: 18, carbs: 28, fat: 16 },
    dietaryTags: ['vegetarian'], allergens: ['egg', 'gluten', 'dairy'], rating: 4.3, popularity: 6,
  },
  {
    title: 'Thai Green Curry',
    description: 'Fragrant coconut curry with chicken, bamboo shoots and Thai basil.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chicken', quantity: 300, unit: 'g', category: 'meat-protein' },
      { name: 'coconut milk', quantity: 400, unit: 'ml', category: 'pantry' },
      { name: 'green curry paste', quantity: 40, unit: 'g', category: 'pantry' },
      { name: 'bell pepper', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'basil', quantity: 10, unit: 'leaves', category: 'spices' },
      { name: 'fish sauce', quantity: 15, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Fry the curry paste in a splash of coconut milk until fragrant.',
      'Add chicken and cook until sealed on all sides.',
      'Pour in remaining coconut milk and simmer 15 minutes.',
      'Add bell pepper and fish sauce; simmer until vegetables are tender.',
      'Finish with fresh basil and serve with jasmine rice.',
    ],
    cuisine: 'asian', category: 'dinner', difficulty: 'medium',
    prepTime: 15, cookTime: 25, servings: 3,
    nutrition: { calories: 510, protein: 30, carbs: 18, fat: 34 },
    dietaryTags: ['gluten-free', 'dairy-free'], allergens: ['fish', 'shellfish'], rating: 4.7, popularity: 8,
  },
  {
    title: 'Greek Salad',
    description: 'Crisp cucumber, tomato, olives and feta tossed in a lemon-oregano dressing.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'cucumber', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'tomato', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'feta cheese', quantity: 100, unit: 'g', category: 'dairy' },
      { name: 'olives', quantity: 50, unit: 'g', category: 'pantry' },
      { name: 'red onion', quantity: 0.5, unit: '', category: 'vegetables' },
      { name: 'olive oil', quantity: 30, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Chop cucumber, tomato and red onion into chunks.',
      'Combine with olives and crumbled feta.',
      'Drizzle with olive oil, oregano, salt and pepper. Toss gently and serve.',
    ],
    cuisine: 'mediterranean', category: 'lunch', difficulty: 'easy',
    prepTime: 10, cookTime: 0, servings: 2,
    nutrition: { calories: 300, protein: 9, carbs: 12, fat: 24 },
    dietaryTags: ['vegetarian', 'gluten-free', 'low-calorie'], allergens: ['dairy'], rating: 4.4, popularity: 6,
  },
  {
    title: 'Korean Bibimbap',
    description: 'Warm rice bowl with sautéed vegetables, a fried egg and gochujang sauce.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'rice', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'carrot', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'spinach', quantity: 80, unit: 'g', category: 'vegetables' },
      { name: 'egg', quantity: 1, unit: '', category: 'meat-protein' },
      { name: 'gochujang', quantity: 20, unit: 'g', category: 'pantry' },
      { name: 'sesame oil', quantity: 10, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Cook rice and set aside.',
      'Blanch spinach and julienne-sauté carrot separately.',
      'Fry the egg sunny-side up.',
      'Arrange rice and vegetables in a bowl, top with egg.',
      'Serve with gochujang and a drizzle of sesame oil, mixing before eating.',
    ],
    cuisine: 'korean', category: 'lunch', difficulty: 'medium',
    prepTime: 15, cookTime: 15, servings: 2,
    nutrition: { calories: 470, protein: 16, carbs: 68, fat: 14 },
    dietaryTags: ['vegetarian', 'dairy-free'], allergens: ['egg', 'soy'], rating: 4.5, popularity: 7,
  },
  {
    title: 'Spaghetti Aglio e Olio',
    description: 'A simple, fast Roman pasta of garlic, olive oil and chili flakes.',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'spaghetti', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'garlic', quantity: 5, unit: 'cloves', category: 'vegetables' },
      { name: 'olive oil', quantity: 60, unit: 'ml', category: 'pantry' },
      { name: 'chili flakes', quantity: 3, unit: 'g', category: 'spices' },
      { name: 'parsley', quantity: 10, unit: 'g', category: 'spices' },
    ],
    instructions: [
      'Cook spaghetti in salted water until al dente, reserve some pasta water.',
      'Gently fry sliced garlic in olive oil until golden, add chili flakes.',
      'Toss the drained pasta into the pan with a splash of pasta water.',
      'Finish with chopped parsley and serve immediately.',
    ],
    cuisine: 'italian', category: 'dinner', difficulty: 'easy',
    prepTime: 5, cookTime: 15, servings: 2,
    nutrition: { calories: 480, protein: 12, carbs: 68, fat: 18 },
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'], allergens: ['gluten'], rating: 4.6, popularity: 8,
  },
  {
    title: 'Chana Masala',
    description: 'A hearty, spiced chickpea curry simmered in onion-tomato gravy.',
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chickpeas', quantity: 400, unit: 'g', category: 'pantry' },
      { name: 'tomato', quantity: 3, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'ginger', quantity: 1, unit: 'inch', category: 'spices' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'vegetables' },
      { name: 'garam masala', quantity: 8, unit: 'g', category: 'spices' },
    ],
    instructions: [
      'Sauté onion, ginger and garlic until golden.',
      'Add tomatoes and cook until they break down into a sauce.',
      'Stir in garam masala and chickpeas with a splash of water.',
      'Simmer 15 minutes until thickened. Serve with rice or roti.',
    ],
    cuisine: 'indian', category: 'dinner', difficulty: 'easy',
    prepTime: 10, cookTime: 25, servings: 3,
    nutrition: { calories: 380, protein: 16, carbs: 55, fat: 10 },
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'high-protein'], allergens: [], rating: 4.5, popularity: 7,
  },
  {
    title: 'Grilled Salmon with Asparagus',
    description: 'Pan-seared salmon fillet with charred asparagus and lemon butter.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'salmon', quantity: 250, unit: 'g', category: 'meat-protein' },
      { name: 'asparagus', quantity: 200, unit: 'g', category: 'vegetables' },
      { name: 'lemon', quantity: 1, unit: '', category: 'fruits' },
      { name: 'butter', quantity: 20, unit: 'g', category: 'dairy' },
      { name: 'garlic', quantity: 2, unit: 'cloves', category: 'vegetables' },
    ],
    instructions: [
      'Season the salmon and sear skin-side down until crisp.',
      'Flip and cook through, about 3-4 minutes.',
      'Sauté asparagus with garlic until just tender.',
      'Finish salmon with butter and lemon juice; serve with asparagus.',
    ],
    cuisine: 'continental', category: 'dinner', difficulty: 'medium',
    prepTime: 10, cookTime: 15, servings: 2,
    nutrition: { calories: 420, protein: 36, carbs: 8, fat: 26 },
    dietaryTags: ['gluten-free', 'keto', 'high-protein'], allergens: ['fish', 'dairy'], rating: 4.8, popularity: 9,
  },
  {
    title: 'Vegetable Fried Rice',
    description: 'Quick wok-fried rice loaded with crisp vegetables and scrambled egg.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'rice', quantity: 250, unit: 'g', category: 'pantry' },
      { name: 'egg', quantity: 2, unit: '', category: 'meat-protein' },
      { name: 'carrot', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'peas', quantity: 80, unit: 'g', category: 'vegetables' },
      { name: 'spring onion', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'soy sauce', quantity: 25, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Scramble the eggs and set aside.',
      'Stir-fry carrot and peas in a hot wok for 2 minutes.',
      'Add cold, day-old rice and break up clumps.',
      'Stir in soy sauce, scrambled egg and spring onion. Toss and serve.',
    ],
    cuisine: 'chinese', category: 'lunch', difficulty: 'easy',
    prepTime: 10, cookTime: 10, servings: 2,
    nutrition: { calories: 430, protein: 14, carbs: 66, fat: 10 },
    dietaryTags: ['vegetarian', 'dairy-free'], allergens: ['egg', 'soy'], rating: 4.3, popularity: 7,
  },
  {
    title: 'Avocado & Egg Breakfast Bowl',
    description: 'Creamy avocado, jammy eggs and cherry tomatoes over greens.',
    image: 'https://images.unsplash.com/photo-1543353071-10c8ba85a904?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'avocado', quantity: 1, unit: '', category: 'fruits' },
      { name: 'egg', quantity: 2, unit: '', category: 'meat-protein' },
      { name: 'cherry tomato', quantity: 100, unit: 'g', category: 'vegetables' },
      { name: 'spinach', quantity: 40, unit: 'g', category: 'vegetables' },
      { name: 'lemon', quantity: 0.5, unit: '', category: 'fruits' },
    ],
    instructions: [
      'Soft boil the eggs for 7 minutes, then peel and halve.',
      'Slice the avocado and halve the cherry tomatoes.',
      'Arrange spinach, avocado, tomatoes and eggs in a bowl.',
      'Squeeze lemon juice on top and season with salt and pepper.',
    ],
    cuisine: 'continental', category: 'breakfast', difficulty: 'easy',
    prepTime: 5, cookTime: 8, servings: 1,
    nutrition: { calories: 360, protein: 16, carbs: 14, fat: 26 },
    dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'keto'], allergens: ['egg'], rating: 4.4, popularity: 6,
  },
  {
    title: 'Mushroom Risotto',
    description: 'Creamy Arborio rice slow-cooked with mushrooms and parmesan.',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'arborio rice', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'mushroom', quantity: 250, unit: 'g', category: 'vegetables' },
      { name: 'onion', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'vegetable stock', quantity: 800, unit: 'ml', category: 'pantry' },
      { name: 'parmesan', quantity: 50, unit: 'g', category: 'dairy' },
      { name: 'butter', quantity: 20, unit: 'g', category: 'dairy' },
    ],
    instructions: [
      'Sauté onion in butter, add rice and toast for 1 minute.',
      'Add warm stock a ladle at a time, stirring until absorbed.',
      'Sauté mushrooms separately and fold in near the end.',
      'Stir in parmesan and remaining butter off the heat. Serve immediately.',
    ],
    cuisine: 'italian', category: 'dinner', difficulty: 'hard',
    prepTime: 10, cookTime: 35, servings: 3,
    nutrition: { calories: 490, protein: 14, carbs: 64, fat: 18 },
    dietaryTags: ['vegetarian', 'gluten-free'], allergens: ['dairy'], rating: 4.6, popularity: 7,
  },
  {
    title: 'Chicken Caesar Salad',
    description: 'Grilled chicken over crisp romaine with parmesan and a creamy Caesar dressing.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chicken', quantity: 200, unit: 'g', category: 'meat-protein' },
      { name: 'romaine lettuce', quantity: 150, unit: 'g', category: 'vegetables' },
      { name: 'parmesan', quantity: 30, unit: 'g', category: 'dairy' },
      { name: 'croutons', quantity: 40, unit: 'g', category: 'pantry' },
      { name: 'caesar dressing', quantity: 40, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Grill the chicken until cooked through, then slice.',
      'Toss romaine with Caesar dressing and parmesan.',
      'Top with sliced chicken and croutons.',
    ],
    cuisine: 'continental', category: 'lunch', difficulty: 'easy',
    prepTime: 10, cookTime: 12, servings: 2,
    nutrition: { calories: 410, protein: 34, carbs: 16, fat: 22 },
    dietaryTags: ['high-protein'], allergens: ['dairy', 'gluten', 'egg'], rating: 4.5, popularity: 7,
  },
  {
    title: 'Vegetable Sushi Rolls',
    description: 'Fresh cucumber, avocado and carrot rolled in seasoned rice and nori.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'sushi rice', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'nori', quantity: 4, unit: 'sheets', category: 'pantry' },
      { name: 'cucumber', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'avocado', quantity: 1, unit: '', category: 'fruits' },
      { name: 'carrot', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'rice vinegar', quantity: 20, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Cook sushi rice and season with rice vinegar; cool to room temperature.',
      'Julienne cucumber, avocado and carrot.',
      'Spread rice on nori, add vegetables and roll tightly with a mat.',
      'Slice into pieces and serve with soy sauce.',
    ],
    cuisine: 'japanese', category: 'lunch', difficulty: 'medium',
    prepTime: 25, cookTime: 15, servings: 2,
    nutrition: { calories: 380, protein: 7, carbs: 72, fat: 8 },
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'], allergens: [], rating: 4.4, popularity: 6,
  },
  {
    title: 'Beef Stir Fry with Broccoli',
    description: 'Tender beef strips and crisp broccoli in a glossy garlic-soy sauce.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'beef', quantity: 300, unit: 'g', category: 'meat-protein' },
      { name: 'broccoli', quantity: 250, unit: 'g', category: 'vegetables' },
      { name: 'garlic', quantity: 3, unit: 'cloves', category: 'vegetables' },
      { name: 'soy sauce', quantity: 40, unit: 'ml', category: 'pantry' },
      { name: 'ginger', quantity: 1, unit: 'inch', category: 'spices' },
      { name: 'sesame oil', quantity: 10, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Slice beef thinly against the grain and sear quickly in a hot wok.',
      'Remove beef, then stir-fry broccoli with garlic and ginger until crisp-tender.',
      'Return beef to the wok, add soy sauce and sesame oil, toss to coat.',
      'Serve with steamed rice.',
    ],
    cuisine: 'chinese', category: 'dinner', difficulty: 'medium',
    prepTime: 15, cookTime: 12, servings: 3,
    nutrition: { calories: 450, protein: 34, carbs: 16, fat: 26 },
    dietaryTags: ['dairy-free', 'high-protein'], allergens: ['soy'], rating: 4.6, popularity: 8,
  },
  {
    title: 'Overnight Oats with Berries',
    description: 'No-cook creamy oats soaked overnight, topped with fresh mixed berries.',
    image: 'https://images.unsplash.com/photo-1517093728432-a0440f8d45af?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'oats', quantity: 60, unit: 'g', category: 'pantry' },
      { name: 'milk', quantity: 150, unit: 'ml', category: 'dairy' },
      { name: 'yogurt', quantity: 60, unit: 'g', category: 'dairy' },
      { name: 'honey', quantity: 15, unit: 'g', category: 'pantry' },
      { name: 'mixed berries', quantity: 80, unit: 'g', category: 'fruits' },
    ],
    instructions: [
      'Combine oats, milk, yogurt and honey in a jar.',
      'Stir well, cover and refrigerate overnight.',
      'Top with fresh berries before serving.',
    ],
    cuisine: 'continental', category: 'breakfast', difficulty: 'easy',
    prepTime: 5, cookTime: 0, servings: 1,
    nutrition: { calories: 320, protein: 12, carbs: 52, fat: 8 },
    dietaryTags: ['vegetarian'], allergens: ['dairy', 'gluten'], rating: 4.4, popularity: 6,
  },
  {
    title: 'Falafel Wrap',
    description: 'Crispy chickpea falafel wrapped in flatbread with fresh salad and tahini sauce.',
    image: 'https://images.unsplash.com/photo-1530910252681-c2c2f4a9b2aa?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chickpeas', quantity: 250, unit: 'g', category: 'pantry' },
      { name: 'flatbread', quantity: 2, unit: '', category: 'pantry' },
      { name: 'cucumber', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'tomato', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'tahini', quantity: 30, unit: 'g', category: 'pantry' },
      { name: 'garlic', quantity: 2, unit: 'cloves', category: 'vegetables' },
    ],
    instructions: [
      'Blend chickpeas, garlic and spices, then form into small patties.',
      'Pan-fry or bake the falafel until golden and crisp.',
      'Whisk tahini with lemon juice and water into a sauce.',
      'Fill the flatbread with falafel, chopped salad and tahini sauce.',
    ],
    cuisine: 'mediterranean', category: 'lunch', difficulty: 'medium',
    prepTime: 15, cookTime: 15, servings: 2,
    nutrition: { calories: 440, protein: 16, carbs: 58, fat: 16 },
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free'], allergens: ['gluten', 'sesame'], rating: 4.5, popularity: 7,
  },
  {
    title: 'Shrimp Pad Thai',
    description: 'Stir-fried rice noodles with shrimp, egg, bean sprouts and tangy tamarind sauce.',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'shrimp', quantity: 200, unit: 'g', category: 'meat-protein' },
      { name: 'rice noodles', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'egg', quantity: 2, unit: '', category: 'meat-protein' },
      { name: 'bean sprouts', quantity: 100, unit: 'g', category: 'vegetables' },
      { name: 'tamarind paste', quantity: 30, unit: 'g', category: 'pantry' },
      { name: 'peanuts', quantity: 30, unit: 'g', category: 'pantry' },
    ],
    instructions: [
      'Soak rice noodles until pliable.',
      'Stir-fry shrimp until pink, push to the side, scramble egg in the same pan.',
      'Add noodles and tamarind sauce, toss until coated.',
      'Fold in bean sprouts and top with crushed peanuts.',
    ],
    cuisine: 'asian', category: 'dinner', difficulty: 'medium',
    prepTime: 15, cookTime: 15, servings: 2,
    nutrition: { calories: 520, protein: 28, carbs: 62, fat: 16 },
    dietaryTags: ['dairy-free'], allergens: ['shellfish', 'egg', 'peanuts'], rating: 4.6, popularity: 8,
  },
  {
    title: 'Caprese Sandwich',
    description: 'Fresh mozzarella, tomato and basil on toasted ciabatta with balsamic glaze.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'ciabatta bread', quantity: 1, unit: '', category: 'pantry' },
      { name: 'mozzarella', quantity: 100, unit: 'g', category: 'dairy' },
      { name: 'tomato', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'basil', quantity: 8, unit: 'leaves', category: 'spices' },
      { name: 'balsamic glaze', quantity: 15, unit: 'ml', category: 'pantry' },
    ],
    instructions: [
      'Slice the ciabatta and lightly toast.',
      'Layer mozzarella, tomato slices and basil leaves.',
      'Drizzle with balsamic glaze and season with salt and pepper.',
    ],
    cuisine: 'italian', category: 'snack', difficulty: 'easy',
    prepTime: 5, cookTime: 3, servings: 1,
    nutrition: { calories: 380, protein: 16, carbs: 40, fat: 16 },
    dietaryTags: ['vegetarian'], allergens: ['dairy', 'gluten'], rating: 4.3, popularity: 5,
  },
  {
    title: 'Lentil Soup',
    description: 'A hearty, warming soup of red lentils, carrots and cumin.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'lentils', quantity: 200, unit: 'g', category: 'pantry' },
      { name: 'carrot', quantity: 2, unit: '', category: 'vegetables' },
      { name: 'onion', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'garlic', quantity: 2, unit: 'cloves', category: 'vegetables' },
      { name: 'vegetable stock', quantity: 800, unit: 'ml', category: 'pantry' },
      { name: 'cumin', quantity: 5, unit: 'g', category: 'spices' },
    ],
    instructions: [
      'Sauté onion, carrot and garlic until softened.',
      'Add lentils, cumin and stock; bring to a boil.',
      'Simmer 20-25 minutes until lentils are tender.',
      'Blend partially for a creamy texture, if desired, and serve.',
    ],
    cuisine: 'mediterranean', category: 'lunch', difficulty: 'easy',
    prepTime: 10, cookTime: 25, servings: 4,
    nutrition: { calories: 260, protein: 16, carbs: 42, fat: 3 },
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'low-calorie'], allergens: [], rating: 4.4, popularity: 6,
  },
  {
    title: 'Keto Zucchini Noodles with Pesto',
    description: 'Spiralized zucchini tossed in basil pesto with cherry tomatoes and pine nuts.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'zucchini', quantity: 3, unit: '', category: 'vegetables' },
      { name: 'basil', quantity: 40, unit: 'g', category: 'spices' },
      { name: 'pine nuts', quantity: 30, unit: 'g', category: 'pantry' },
      { name: 'parmesan', quantity: 40, unit: 'g', category: 'dairy' },
      { name: 'olive oil', quantity: 50, unit: 'ml', category: 'pantry' },
      { name: 'cherry tomato', quantity: 100, unit: 'g', category: 'vegetables' },
    ],
    instructions: [
      'Spiralize the zucchini into noodles.',
      'Blend basil, pine nuts, parmesan and olive oil into a smooth pesto.',
      'Toss zucchini noodles with pesto and halved cherry tomatoes.',
      'Serve immediately, raw or lightly warmed.',
    ],
    cuisine: 'italian', category: 'dinner', difficulty: 'easy',
    prepTime: 15, cookTime: 0, servings: 2,
    nutrition: { calories: 340, protein: 10, carbs: 12, fat: 28 },
    dietaryTags: ['vegetarian', 'gluten-free', 'keto', 'low-calorie'], allergens: ['dairy', 'nuts'], rating: 4.5, popularity: 6,
  },
  {
    title: 'Protein Pancakes',
    description: 'Fluffy banana-oat pancakes packed with protein for a hearty breakfast.',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'oats', quantity: 80, unit: 'g', category: 'pantry' },
      { name: 'banana', quantity: 1, unit: '', category: 'fruits' },
      { name: 'egg', quantity: 2, unit: '', category: 'meat-protein' },
      { name: 'milk', quantity: 60, unit: 'ml', category: 'dairy' },
      { name: 'honey', quantity: 15, unit: 'g', category: 'pantry' },
    ],
    instructions: [
      'Blend oats, banana, eggs and milk until smooth.',
      'Cook small ladles of batter on a lightly oiled pan until bubbles form.',
      'Flip and cook the other side until golden.',
      'Stack and drizzle with honey.',
    ],
    cuisine: 'continental', category: 'breakfast', difficulty: 'easy',
    prepTime: 10, cookTime: 10, servings: 2,
    nutrition: { calories: 360, protein: 18, carbs: 48, fat: 10 },
    dietaryTags: ['vegetarian', 'high-protein'], allergens: ['egg', 'dairy', 'gluten'], rating: 4.4, popularity: 6,
  },
  {
    title: 'Hummus & Veggie Snack Plate',
    description: 'Creamy homemade hummus with crunchy fresh vegetable sticks.',
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85',
    ingredients: [
      { name: 'chickpeas', quantity: 250, unit: 'g', category: 'pantry' },
      { name: 'tahini', quantity: 30, unit: 'g', category: 'pantry' },
      { name: 'garlic', quantity: 1, unit: 'clove', category: 'vegetables' },
      { name: 'lemon', quantity: 1, unit: '', category: 'fruits' },
      { name: 'carrot', quantity: 1, unit: '', category: 'vegetables' },
      { name: 'cucumber', quantity: 1, unit: '', category: 'vegetables' },
    ],
    instructions: [
      'Blend chickpeas, tahini, garlic and lemon juice until smooth, adding water as needed.',
      'Season with salt and a drizzle of olive oil.',
      'Cut carrot and cucumber into sticks and serve alongside.',
    ],
    cuisine: 'mediterranean', category: 'snack', difficulty: 'easy',
    prepTime: 10, cookTime: 0, servings: 3,
    nutrition: { calories: 220, protein: 8, carbs: 24, fat: 10 },
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'], allergens: ['sesame'], rating: 4.3, popularity: 5,
  },
];

module.exports = recipes;
